"""workout sessions, items, measurements

Revision ID: 579f7066c156
Revises: ef7a23211ee2
Create Date: 2026-10-02 14:22:46.876468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579f7066c156'
down_revision: Union[str, Sequence[str], None] = 'ef7a23211ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('session_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'in_progress', 'completed')", name='ck_workout_session_status'),
    sa.CheckConstraint('intensity BETWEEN 1 AND 10', name='ck_workout_session_intensity'),
    sa.ForeignKeyConstraint(['source_session_id'], ['workout_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_sessions_user_id_session_at', 'workout_sessions', ['user_id', 'session_at'], unique=False)
    op.create_table('workout_session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_session_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_item_id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('planned_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('set_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_item_id'], ['workout_session_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_session_measurements')
    op.drop_table('workout_session_items')
    op.drop_index('ix_workout_sessions_user_id_session_at', table_name='workout_sessions')
    op.drop_table('workout_sessions')
    # ### end Alembic commands ###
