"""workout plans

Revision ID: c3edbccda4d2
Revises: 585685e32f99
Create Date: 2026-10-02 18:53:58.163386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3edbccda4d2'
down_revision: Union[str, Sequence[str], None] = '585685e32f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('length_weeks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    op.add_column('workout_sessions', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workout_sessions_plan_id'), 'workout_sessions', ['plan_id'], unique=False)
    op.create_foreign_key('fk_workout_sessions_plan_id', 'workout_sessions', 'workout_plans', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workout_sessions_plan_id', 'workout_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_workout_sessions_plan_id'), table_name='workout_sessions')
    op.drop_column('workout_sessions', 'plan_id')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    # ### end Alembic commands ###
